version: "3"

services:
    
    hadoop_hbase:
        container_name: pts-hbase
        image: sestakmartina/hadoop-hbase:latest
        ports:
            - "8088:8088"
            - "9870:9870"
            - "8047:8047"
        networks:
            - pts-net


networks:
    pts-net:
        driver: bridge



