version: "3"

services:
    
    hadoop_base:
        container_name: pts-hadoop
        image: sestakmartina/hadoop-sqoop:0.3
        ports:
            - "8088:8088"
            - "9870:9870"
        networks:
            - pts-net


networks:
    pts-net:
        driver: bridge



